"""init schema v0.0.1

Revision ID: cb2b21f96f77
Revises: 
Create Date: 2025-08-24 19:50:03.319861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2b21f96f77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_full_name'), 'author', ['full_name'], unique=False)
    op.create_index(op.f('ix_author_id'), 'author', ['id'], unique=False)
    op.create_table('genre',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genre_id'), 'genre', ['id'], unique=False)
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=True)
    op.create_table('member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_email'), 'member', ['email'], unique=True)
    op.create_index(op.f('ix_member_full_name'), 'member', ['full_name'], unique=False)
    op.create_index(op.f('ix_member_id'), 'member', ['id'], unique=False)
    op.create_table('publisher',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publisher_id'), 'publisher', ['id'], unique=False)
    op.create_index(op.f('ix_publisher_name'), 'publisher', ['name'], unique=True)
    op.create_table('book',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('isbn_13', sa.String(length=13), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_id'), 'book', ['id'], unique=False)
    op.create_index(op.f('ix_book_isbn_13'), 'book', ['isbn_13'], unique=True)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=False)
    op.create_table('book_author_link',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.create_table('book_genre_link',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    op.create_table('copy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copy_book_id'), 'copy', ['book_id'], unique=False)
    op.create_index(op.f('ix_copy_id'), 'copy', ['id'], unique=False)
    op.create_index(op.f('ix_copy_inventory_code'), 'copy', ['inventory_code'], unique=True)
    op.create_table('hold',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fulfilled_copy_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['fulfilled_copy_id'], ['copy.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hold_book_id'), 'hold', ['book_id'], unique=False)
    op.create_index(op.f('ix_hold_id'), 'hold', ['id'], unique=False)
    op.create_index(op.f('ix_hold_member_id'), 'hold', ['member_id'], unique=False)
    op.create_table('loan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('copy_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('loan_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['copy_id'], ['copy.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_copy_id'), 'loan', ['copy_id'], unique=False)
    op.create_index(op.f('ix_loan_id'), 'loan', ['id'], unique=False)
    op.create_index(op.f('ix_loan_member_id'), 'loan', ['member_id'], unique=False)
    op.create_table('fine',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('loan_id', sa.Uuid(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fine_id'), 'fine', ['id'], unique=False)
    op.create_index(op.f('ix_fine_member_id'), 'fine', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fine_member_id'), table_name='fine')
    op.drop_index(op.f('ix_fine_id'), table_name='fine')
    op.drop_table('fine')
    op.drop_index(op.f('ix_loan_member_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_id'), table_name='loan')
    op.drop_index(op.f('ix_loan_copy_id'), table_name='loan')
    op.drop_table('loan')
    op.drop_index(op.f('ix_hold_member_id'), table_name='hold')
    op.drop_index(op.f('ix_hold_id'), table_name='hold')
    op.drop_index(op.f('ix_hold_book_id'), table_name='hold')
    op.drop_table('hold')
    op.drop_index(op.f('ix_copy_inventory_code'), table_name='copy')
    op.drop_index(op.f('ix_copy_id'), table_name='copy')
    op.drop_index(op.f('ix_copy_book_id'), table_name='copy')
    op.drop_table('copy')
    op.drop_table('book_genre_link')
    op.drop_table('book_author_link')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_isbn_13'), table_name='book')
    op.drop_index(op.f('ix_book_id'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_publisher_name'), table_name='publisher')
    op.drop_index(op.f('ix_publisher_id'), table_name='publisher')
    op.drop_table('publisher')
    op.drop_index(op.f('ix_member_id'), table_name='member')
    op.drop_index(op.f('ix_member_full_name'), table_name='member')
    op.drop_index(op.f('ix_member_email'), table_name='member')
    op.drop_table('member')
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.drop_index(op.f('ix_genre_id'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_author_id'), table_name='author')
    op.drop_index(op.f('ix_author_full_name'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
